// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolWebApp.Dal.Entities;

#nullable disable

namespace SchoolWebApp.Dal.Migrations
{
    [DbContext(typeof(SchoolWebAppDatabaseContext))]
    [Migration("20260728203234_AjoutSexeEleve")]
    partial class AjoutSexeEleve
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("CodeEduscol")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code_eduscol");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Domaine")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("domaine");

                    b.Property<string>("Libelle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("libelle");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<int>("NiveauScolaireId")
                        .HasColumnType("int")
                        .HasColumnName("niveau_scolaire_id");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.HasIndex("NiveauScolaireId");

                    b.HasIndex("MatiereId", "NiveauScolaireId");

                    b.ToTable("Competence", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.CompetencePrerequis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int")
                        .HasColumnName("competence_id");

                    b.Property<int>("Poids")
                        .HasColumnType("int")
                        .HasColumnName("poids");

                    b.Property<int>("PrerequisId")
                        .HasColumnType("int")
                        .HasColumnName("prerequis_id");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisId");

                    b.HasIndex("CompetenceId", "PrerequisId")
                        .IsUnique();

                    b.ToTable("CompetencePrerequis", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateDernierMessage")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_dernier_message");

                    b.Property<DateTime?>("DatePurge")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_purge");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<string>("Titre")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.HasIndex("DatePurge");

                    b.HasIndex("MatiereId");

                    b.HasIndex("EleveId", "DateDernierMessage");

                    b.ToTable("Conversation", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Eleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DerniereActivite")
                        .HasColumnType("datetime2")
                        .HasColumnName("derniere_activite");

                    b.Property<int>("NiveauScolaireId")
                        .HasColumnType("int")
                        .HasColumnName("niveau_scolaire_id");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<int>("Sexe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sexe");

                    b.HasKey("Id");

                    b.HasIndex("NiveauScolaireId");

                    b.HasIndex("ParentId");

                    b.ToTable("Eleve", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.MaitriseEleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int")
                        .HasColumnName("competence_id");

                    b.Property<double>("Confiance")
                        .HasColumnType("float")
                        .HasColumnName("confiance");

                    b.Property<DateTime>("DerniereEvaluation")
                        .HasColumnType("datetime2")
                        .HasColumnName("derniere_evaluation");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<int>("NombreObservations")
                        .HasColumnType("int")
                        .HasColumnName("nombre_observations");

                    b.Property<DateTime?>("ProchaineRevision")
                        .HasColumnType("datetime2")
                        .HasColumnName("prochaine_revision");

                    b.Property<double>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("ProchaineRevision");

                    b.HasIndex("EleveId", "CompetenceId")
                        .IsUnique();

                    b.ToTable("MaitriseEleve", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("AgentSlug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("agent_slug");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Libelle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("libelle");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.Property<string>("ProfAvatar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prof_avatar");

                    b.Property<string>("ProfCouleur")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prof_couleur");

                    b.Property<string>("ProfPrenom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prof_prenom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("Matiere", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("Modele")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modele");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int>("TokensCacheEcriture")
                        .HasColumnType("int")
                        .HasColumnName("tokens_cache_ecriture");

                    b.Property<int>("TokensCacheLecture")
                        .HasColumnType("int")
                        .HasColumnName("tokens_cache_lecture");

                    b.Property<int>("TokensEntree")
                        .HasColumnType("int")
                        .HasColumnName("tokens_entree");

                    b.Property<int>("TokensSortie")
                        .HasColumnType("int")
                        .HasColumnName("tokens_sortie");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "DateCreation");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.NiveauScolaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("Cycle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cycle");

                    b.Property<string>("Libelle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("libelle");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("NiveauScolaire", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mail");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("Mail")
                        .IsUnique()
                        .HasFilter("[mail] IS NOT NULL");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Competence", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Competences")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.NiveauScolaire", "NiveauScolaire")
                        .WithMany("Competences")
                        .HasForeignKey("NiveauScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("NiveauScolaire");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.CompetencePrerequis", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Competence", "Competence")
                        .WithMany("Prerequis")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Competence", "Prerequis")
                        .WithMany("Successeurs")
                        .HasForeignKey("PrerequisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Prerequis");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Conversation", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Conversations")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Conversations")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.NiveauScolaire", "NiveauScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("NiveauScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Parent", "Parent")
                        .WithMany("Eleves")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NiveauScolaire");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.MaitriseEleve", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Competence", "Competence")
                        .WithMany("Maitrises")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Maitrises")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Message", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Competence", b =>
                {
                    b.Navigation("Maitrises");

                    b.Navigation("Prerequis");

                    b.Navigation("Successeurs");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Eleve", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Maitrises");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Matiere", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.NiveauScolaire", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Parent", b =>
                {
                    b.Navigation("Eleves");
                });
#pragma warning restore 612, 618
        }
    }
}
