// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolWebApp.Dal.Entities;

#nullable disable

namespace SchoolWebApp.Dal.Migrations
{
    [DbContext(typeof(SchoolWebAppDatabaseContext))]
    [Migration("20260808005654_CodeParent")]
    partial class CodeParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlerteQuotaEnvoyee")
                        .HasColumnType("bit")
                        .HasColumnName("alerte_quota_envoyee");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_fin");

                    b.Property<DateTime?>("DernierePause")
                        .HasColumnType("datetime2")
                        .HasColumnName("derniere_pause");

                    b.Property<int>("OffreId")
                        .HasColumnType("int")
                        .HasColumnName("offre_id");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("PauseJusquau")
                        .HasColumnType("datetime2")
                        .HasColumnName("pause_jusquau");

                    b.Property<DateTime>("PeriodeDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("periode_debut");

                    b.Property<DateTime>("PeriodeFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("periode_fin");

                    b.Property<string>("Periodicite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Mensuel")
                        .HasColumnName("periodicite");

                    b.Property<DateTime?>("ResiliationDemandeeLe")
                        .HasColumnType("datetime2")
                        .HasColumnName("resiliation_demandee_le");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("statut");

                    b.HasKey("Id");

                    b.HasIndex("OffreId");

                    b.HasIndex("PeriodeFin");

                    b.HasIndex("ParentId", "Statut");

                    b.ToTable("Abonnement", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("CodeEduscol")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code_eduscol");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Domaine")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("domaine");

                    b.Property<string>("Libelle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("libelle");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<int>("NiveauScolaireId")
                        .HasColumnType("int")
                        .HasColumnName("niveau_scolaire_id");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.HasIndex("NiveauScolaireId");

                    b.HasIndex("MatiereId", "NiveauScolaireId");

                    b.ToTable("Competence", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.CompetencePrerequis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int")
                        .HasColumnName("competence_id");

                    b.Property<int>("Poids")
                        .HasColumnType("int")
                        .HasColumnName("poids");

                    b.Property<int>("PrerequisId")
                        .HasColumnType("int")
                        .HasColumnName("prerequis_id");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisId");

                    b.HasIndex("CompetenceId", "PrerequisId")
                        .IsUnique();

                    b.ToTable("CompetencePrerequis", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.ConsommationEleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonnementId")
                        .HasColumnType("int")
                        .HasColumnName("abonnement_id");

                    b.Property<DateTime>("DerniereActivite")
                        .HasColumnType("datetime2")
                        .HasColumnName("derniere_activite");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<DateTime>("PeriodeDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("periode_debut");

                    b.Property<int>("SecondesConsommees")
                        .HasColumnType("int")
                        .HasColumnName("secondes_consommees");

                    b.HasKey("Id");

                    b.HasIndex("EleveId");

                    b.HasIndex("AbonnementId", "EleveId", "PeriodeDebut")
                        .IsUnique();

                    b.ToTable("ConsommationEleve", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateDernierMessage")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_dernier_message");

                    b.Property<DateTime?>("DateDerniereObservation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_derniere_observation");

                    b.Property<DateTime?>("DatePurge")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_purge");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_sortie");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<string>("Titre")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.HasIndex("DatePurge");

                    b.HasIndex("MatiereId");

                    b.HasIndex("EleveId", "DateDernierMessage");

                    b.ToTable("Conversation", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Eleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime?>("AnonymiseLe")
                        .HasColumnType("datetime2")
                        .HasColumnName("anonymise_le");

                    b.Property<DateTime?>("ArchiveLe")
                        .HasColumnType("datetime2")
                        .HasColumnName("archive_le");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DerniereActivite")
                        .HasColumnType("datetime2")
                        .HasColumnName("derniere_activite");

                    b.Property<int>("NiveauScolaireId")
                        .HasColumnType("int")
                        .HasColumnName("niveau_scolaire_id");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<int>("Sexe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sexe");

                    b.HasKey("Id");

                    b.HasIndex("NiveauScolaireId");

                    b.HasIndex("ParentId");

                    b.ToTable("Eleve", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ARevoir")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("a_revoir");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<double>("Note")
                        .HasColumnType("float")
                        .HasColumnName("note");

                    b.Property<string>("Notion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notion");

                    b.Property<string>("Remarque")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("remarque");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("EleveId", "DateCreation");

                    b.ToTable("Evaluation", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.FicheRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime?>("DateConsultation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_consultation");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_mise_a_jour");

                    b.Property<string>("Domaine")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("domaine");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<string>("Etat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("etat");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<string>("Notion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notion");

                    b.HasKey("Id");

                    b.HasIndex("MatiereId");

                    b.HasIndex("EleveId", "MatiereId", "DateMiseAJour");

                    b.HasIndex("EleveId", "MatiereId", "Notion")
                        .IsUnique();

                    b.ToTable("FicheRevision", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.MaitriseEleve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int")
                        .HasColumnName("competence_id");

                    b.Property<double>("Confiance")
                        .HasColumnType("float")
                        .HasColumnName("confiance");

                    b.Property<DateTime>("DerniereEvaluation")
                        .HasColumnType("datetime2")
                        .HasColumnName("derniere_evaluation");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<int>("NombreObservations")
                        .HasColumnType("int")
                        .HasColumnName("nombre_observations");

                    b.Property<DateTime?>("ProchaineRevision")
                        .HasColumnType("datetime2")
                        .HasColumnName("prochaine_revision");

                    b.Property<double>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("ProchaineRevision");

                    b.HasIndex("EleveId", "CompetenceId")
                        .IsUnique();

                    b.ToTable("MaitriseEleve", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Matiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("AgentSlug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("agent_slug");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Libelle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("libelle");

                    b.Property<int>("NiveauOrdreMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12)
                        .HasColumnName("niveau_ordre_max");

                    b.Property<int>("NiveauOrdreMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("niveau_ordre_min");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.Property<string>("ProfAvatar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prof_avatar");

                    b.Property<string>("ProfCouleur")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prof_couleur");

                    b.Property<string>("ProfPrenom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prof_prenom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("Matiere", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("Modele")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modele");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<int>("TokensCacheEcriture")
                        .HasColumnType("int")
                        .HasColumnName("tokens_cache_ecriture");

                    b.Property<int>("TokensCacheLecture")
                        .HasColumnType("int")
                        .HasColumnName("tokens_cache_lecture");

                    b.Property<int>("TokensEntree")
                        .HasColumnType("int")
                        .HasColumnName("tokens_entree");

                    b.Property<int>("TokensSortie")
                        .HasColumnType("int")
                        .HasColumnName("tokens_sortie");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "DateCreation");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.NiveauScolaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("Cycle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cycle");

                    b.Property<string>("Libelle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("libelle");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("NiveauScolaire", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accroche")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("accroche");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<bool>("EstEssai")
                        .HasColumnType("bit")
                        .HasColumnName("est_essai");

                    b.Property<int>("JoursValidite")
                        .HasColumnType("int")
                        .HasColumnName("jours_validite");

                    b.Property<string>("Libelle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("libelle");

                    b.Property<int>("MinutesPlafondEnfant")
                        .HasColumnType("int")
                        .HasColumnName("minutes_plafond_enfant");

                    b.Property<int>("MinutesPotMensuel")
                        .HasColumnType("int")
                        .HasColumnName("minutes_pot_mensuel");

                    b.Property<int>("NombreEnfantsMax")
                        .HasColumnType("int")
                        .HasColumnName("nombre_enfants_max");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.Property<int>("PrixAnnuelCentimes")
                        .HasColumnType("int")
                        .HasColumnName("prix_annuel_centimes");

                    b.Property<int>("PrixMensuelCentimes")
                        .HasColumnType("int")
                        .HasColumnName("prix_mensuel_centimes");

                    b.Property<string>("StripePrixAnnuelId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("stripe_prix_annuel_id");

                    b.Property<string>("StripePrixMensuelId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("stripe_prix_mensuel_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Offre", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.OffreRecharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Libelle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("libelle");

                    b.Property<int>("Minutes")
                        .HasColumnType("int")
                        .HasColumnName("minutes");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.Property<int>("PrixCentimes")
                        .HasColumnType("int")
                        .HasColumnName("prix_centimes");

                    b.Property<string>("StripePrixId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("stripe_prix_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OffreRecharge", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeParent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("code_parent");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mail");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("Mail")
                        .IsUnique()
                        .HasFilter("[mail] IS NOT NULL");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.PieceJointe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<byte[]>("Donnees")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("donnees");

                    b.Property<DateTime?>("DonneesEffaceesLe")
                        .HasColumnType("datetime2")
                        .HasColumnName("donnees_effacees_le");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<string>("NomFichier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_fichier");

                    b.Property<int>("NombrePages")
                        .HasColumnType("int")
                        .HasColumnName("nombre_pages");

                    b.Property<int>("Taille")
                        .HasColumnType("int")
                        .HasColumnName("taille");

                    b.Property<string>("Transcription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcription");

                    b.Property<string>("TypeMime")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type_mime");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ConversationId", "DateCreation");

                    b.HasIndex("DonneesEffaceesLe", "DateCreation");

                    b.ToTable("PieceJointe", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.PlancheSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auteur")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auteur");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("cle");

                    b.Property<string>("Contenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_modification");

                    b.Property<byte[]>("Donnees")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("donnees");

                    b.Property<string>("Licence")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("licence");

                    b.Property<string>("MatiereCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("matiere_code");

                    b.Property<string>("NomFichier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom_fichier");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("source");

                    b.Property<int>("Taille")
                        .HasColumnType("int")
                        .HasColumnName("taille");

                    b.Property<string>("TypeMime")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type_mime");

                    b.HasKey("Id");

                    b.HasIndex("Cle")
                        .IsUnique();

                    b.HasIndex("MatiereCode");

                    b.ToTable("PlancheSchema", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.RapportSeance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ARevoir")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("a_revoir");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<int>("EleveId")
                        .HasColumnType("int")
                        .HasColumnName("eleve_id");

                    b.Property<int>("MatiereId")
                        .HasColumnType("int")
                        .HasColumnName("matiere_id");

                    b.Property<double?>("NoteComprehension")
                        .HasColumnType("float")
                        .HasColumnName("note_comprehension");

                    b.Property<double?>("NoteRevision")
                        .HasColumnType("float")
                        .HasColumnName("note_revision");

                    b.Property<string>("Remarque")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("remarque");

                    b.Property<string>("Travaille")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("travaille");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MatiereId");

                    b.HasIndex("EleveId", "DateCreation");

                    b.ToTable("RapportSeance", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Recharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonnementId")
                        .HasColumnType("int")
                        .HasColumnName("abonnement_id");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_achat");

                    b.Property<int>("Minutes")
                        .HasColumnType("int")
                        .HasColumnName("minutes");

                    b.Property<DateTime>("PeriodeDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("periode_debut");

                    b.Property<int>("PrixCentimes")
                        .HasColumnType("int")
                        .HasColumnName("prix_centimes");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementId", "PeriodeDebut");

                    b.ToTable("Recharge", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Reglage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("cle");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_modification");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("valeur");

                    b.HasKey("Id");

                    b.HasIndex("Cle")
                        .IsUnique();

                    b.ToTable("Reglage", (string)null);
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Abonnement", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Offre", "Offre")
                        .WithMany("Abonnements")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Parent", "Parent")
                        .WithMany("Abonnements")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Competence", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Competences")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.NiveauScolaire", "NiveauScolaire")
                        .WithMany("Competences")
                        .HasForeignKey("NiveauScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("NiveauScolaire");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.CompetencePrerequis", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Competence", "Competence")
                        .WithMany("Prerequis")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Competence", "Prerequis")
                        .WithMany("Successeurs")
                        .HasForeignKey("PrerequisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Prerequis");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.ConsommationEleve", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Abonnement", "Abonnement")
                        .WithMany("Consommations")
                        .HasForeignKey("AbonnementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Consommations")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Abonnement");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Conversation", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Conversations")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Conversations")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Eleve", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.NiveauScolaire", "NiveauScolaire")
                        .WithMany("Eleves")
                        .HasForeignKey("NiveauScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Parent", "Parent")
                        .WithMany("Eleves")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NiveauScolaire");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Evaluation", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Conversation", "Conversation")
                        .WithMany("Evaluations")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Evaluations")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Evaluations")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.FicheRevision", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Fiches")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Fiches")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.MaitriseEleve", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Competence", "Competence")
                        .WithMany("Maitrises")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Maitrises")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Message", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.PieceJointe", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Conversation");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.RapportSeance", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Conversation", "Conversation")
                        .WithMany("Rapports")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Eleve", "Eleve")
                        .WithMany("Rapports")
                        .HasForeignKey("EleveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolWebApp.Dal.Entities.Matiere", "Matiere")
                        .WithMany("Rapports")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Eleve");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Recharge", b =>
                {
                    b.HasOne("SchoolWebApp.Dal.Entities.Abonnement", "Abonnement")
                        .WithMany("Recharges")
                        .HasForeignKey("AbonnementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonnement");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Abonnement", b =>
                {
                    b.Navigation("Consommations");

                    b.Navigation("Recharges");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Competence", b =>
                {
                    b.Navigation("Maitrises");

                    b.Navigation("Prerequis");

                    b.Navigation("Successeurs");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Conversation", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Messages");

                    b.Navigation("Rapports");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Eleve", b =>
                {
                    b.Navigation("Consommations");

                    b.Navigation("Conversations");

                    b.Navigation("Evaluations");

                    b.Navigation("Fiches");

                    b.Navigation("Maitrises");

                    b.Navigation("Rapports");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Matiere", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("Conversations");

                    b.Navigation("Evaluations");

                    b.Navigation("Fiches");

                    b.Navigation("Rapports");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.NiveauScolaire", b =>
                {
                    b.Navigation("Competences");

                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Offre", b =>
                {
                    b.Navigation("Abonnements");
                });

            modelBuilder.Entity("SchoolWebApp.Dal.Entities.Parent", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Eleves");
                });
#pragma warning restore 612, 618
        }
    }
}
